using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace IoT.Backend.Models;

/// <summary>
/// Alert entity - represents system alerts for coordinators and towers.
/// Auto-generated by AlertService based on telemetry anomalies.
/// </summary>
public class Alert
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = ObjectId.GenerateNewId().ToString();
    
    /// <summary>
    /// Farm that this alert belongs to.
    /// </summary>
    [BsonElement("farm_id")]
    public string FarmId { get; set; } = string.Empty;
    
    /// <summary>
    /// Coordinator ID if alert is related to a coordinator (null if tower-specific).
    /// </summary>
    [BsonElement("coord_id")]
    public string? CoordId { get; set; }
    
    /// <summary>
    /// Tower ID if alert is related to a tower (null if coordinator-specific).
    /// </summary>
    [BsonElement("tower_id")]
    public string? TowerId { get; set; }
    
    /// <summary>
    /// Severity level: critical, warning, info.
    /// </summary>
    [BsonElement("severity")]
    public string Severity { get; set; } = "info";
    
    /// <summary>
    /// Alert status: active, acknowledged, resolved.
    /// </summary>
    [BsonElement("status")]
    public string Status { get; set; } = "active";
    
    /// <summary>
    /// Human-readable alert message.
    /// </summary>
    [BsonElement("message")]
    public string Message { get; set; } = string.Empty;
    
    /// <summary>
    /// Alert category: battery, temperature, connectivity, water, pump, etc.
    /// </summary>
    [BsonElement("category")]
    public string Category { get; set; } = string.Empty;
    
    /// <summary>
    /// When the alert was created.
    /// </summary>
    [BsonElement("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// When the alert was acknowledged (null if not acknowledged).
    /// </summary>
    [BsonElement("acknowledged_at")]
    public DateTime? AcknowledgedAt { get; set; }
    
    /// <summary>
    /// Who acknowledged the alert (user ID or system).
    /// </summary>
    [BsonElement("acknowledged_by")]
    public string? AcknowledgedBy { get; set; }
    
    /// <summary>
    /// When the alert was resolved (null if not resolved).
    /// </summary>
    [BsonElement("resolved_at")]
    public DateTime? ResolvedAt { get; set; }
    
    /// <summary>
    /// Additional metadata (e.g., sensor values, thresholds).
    /// </summary>
    [BsonElement("metadata")]
    public Dictionary<string, object>? Metadata { get; set; }
    
    /// <summary>
    /// Unique key to prevent duplicate alerts (e.g., "battery_low_tower123").
    /// </summary>
    [BsonElement("alert_key")]
    public string? AlertKey { get; set; }
}
